version: "3.3"
services:
  db:
    image: mysql:8.4
    restart: always
    container_name: mysql-db
    #user: "1000:1000"
    environment:
      MYSQL_DATABASE: db_springboot_cloud
      # So you don't have to use root, but you can if you like
      MYSQL_USER: fchavez
      # You can use whatever password you like
      MYSQL_PASSWORD: pa$$word
      # Password for root access
      MYSQL_ROOT_PASSWORD: root
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
# Names our volume
volumes:
  my-db:
